config/routes.rb
Rails.application.routes.draw do

  root "application#index"

  devise_for :admins, path: "", path_names: { sign_in: "admin/signin", sign_out: "admin/signout" }

  namespace :admin do
    resource :dashboard, only: [:show]
  end

  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      resources :groups,
                :trips,
                :itinerary
    end
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, # :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout "admin"
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < Admin::BaseController
  def show

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_admin!

  def index
    redirect_to admin_dashboard_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title Tropa Trips
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.3.0/css/material-fullpalette.css', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    = render "layouts/admin/nav"

    .container
      .row
        .col-lg-4
          = render "layouts/admin/sidebar"

        .col-lg-8
          = yield

    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.3.0/js/material.js', 'data-turbolinks-track' => true

app/views/layouts/admin/_nav.html.haml
.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle{ type: "button", "data-toggle" => "collapse", "data-target" => ".navbar-responsive-collapse" }
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      = link_to "Tropa Trips", root_path, class: "navbar-brand"

    .navbar-collapse.collapse.navbar-responsive-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to "Hi Admin", "#"

        %li
          = link_to "Sign out", destroy_admin_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tropa Trips
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.3.0/css/material-fullpalette.css', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    - if admin_signed_in?
      = render "layouts/nav"

    .container
      .row
        .col-lg-12
          = yield

    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.3.0/js/material.js', 'data-turbolinks-track' => true